### ISSUE TITLE
"minItems" placement in JSON Schemas

### ISSUE THREAD

**Issue by jmfernandez** [fairtracks/fairtracks_standard#3]
Having a look at https://github.com/fairtracks/fairtracks_standard/blob/b5f7f588659c9a0850127fa4cbd0781241240f12/json/schema/ I have realized that the "minItems" declarations (for instance, https://github.com/fairtracks/fairtracks_standard/blob/b5f7f588659c9a0850127fa4cbd0781241240f12/json/schema/fairtracks.schema.json#L13-L19) should be at the same level of "items" declarations, and not inside.

**Comment by sveinugu** [comment]
Fixed by 3f7fd5ed28bd357636724213a8950810c8c56360.
