### ISSUE TITLE
Create an track collection metadata section with optional trackhub name and id

### ISSUE THREAD

**Issue by sveinugu** [fairtracks/fairtracks_standard#9]
Should go into the top-level schema. Will represent the "investigation" level of the ISA model, while Study=study and Assay=experiment

**Comment by sveinugu** [comment]
@dzerbino @jmfernandez This should probably have been a pull request, as it adds quite a bit of additional fields, but I forgot about it in the hurry. Please review the commit for details and comment here (and possible reopen).

**Comment by jmfernandez** [comment]
There are some issues in the generated JSON Schema, as you can see in `description_url` declaration:

https://github.com/fairtracks/fairtracks_standard/blob/0b1a3adfdc53094e50f16ff88d1b5056cf7d1380/json/schema/fairtracks.schema.json#L48-L71
